jwt:
    secret: aG51mfbYiVoX6hzSLfQQfCfsXuH5tTkvMwJM28u5p552f7ngBump1GWoXC5HPHoozyvJ9VzeYbRhLONC3jNcZa

logging:
    level:
        org.springframework.security: DEBUG
        liquibase: DEBUG

spring:
    application:
        name: Simple Shop
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/simpleshop
        username: admin
        password: password
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.xml
